### ISSUE TITLE
lightning RPC error

### ISSUE THREAD

**Issue by jasonshen2011121** [pingcap/docs-cn#1092] opened 2019-01-22 11:09 UTC
Hi ,
Our biggest concern before about using TIDB is it has no fast recovery solution.
we know lighting is online, then we decide to test it. 
We followed the instructions but after executed the command start_lightning.sh, error in log below.
We have no idea at all how this happens and how to resolve.
Could you please take a look at the error info below and do us a favor?
Thanks in advance!

```
2019/01/22 07:57:31.325 lightning.go:59: [info] cfg {"lightning":{"level":"info","file":"log/tidb_lightning.log","max-size":128,"max-days":28,"max-backups":14,"table-concurrency":8,"region-concurrency":8,"pprof-port":10089,"check-requirements":true},"tidb":{"host":"172.0.24.117","port":4000,"user":"root","status-port":10080,"pd-addr":"172.0.12.55:2379","sql-mode":"STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION","log-level":"error","distsql-scan-concurrency":16},"checkpoint":{"enable":true,"schema":"tidb_lightning_checkpoint","keep-after-success":false},"mydumper":{"read-block-size":4096,"region-min-size":268435456,"data-source-dir":"/data1/deploy/mydumper","no-schema":false,"character-set":"auto"},"black-white-list":null,"tikv-importer":{"addr":"172.0.12.63:20170","batch-size":500},"post-restore":{"compact":true,"checksum":true,"analyze":true},"config-file":"./conf/tidb-lightning.toml"}
2019/01/22 07:57:34.367 restore.go:182: [error] run cause error : rpc error: code = Unknown desc = Grpc(RpcFailure(RpcStatus { status: Unavailable, details: Some("Connect Failed") }))
```

**Comment by dcalvin** [comment] 2019-04-04 06:34
@kennytm Could you help look at this?

**Comment by kennytm** [comment] 2019-04-04 06:41
Sorry there is not enough information to tell what is the cause of connection failure. Perhaps check whether the Lightning machine can correctly connect to all mentioned services? -

* TiDB at `172.0.24.117:4000` and `172.0.24.117:10080`
* PD at `172.0.12.55:2379`
* Importer at `172.0.12.63:20170`

**Comment by dcalvin** [comment] 2019-04-17 08:57
@jasonshen2011121 Please check the comments above. Thanks.

**Comment by yikeke** [comment] 2019-11-01 03:44
Hi @jasonshen2011121 , because this issue is too old, I'll close it for now. Feel free to reopen it if you have any further questions~

**Closed by yikeke** 2019-11-01 03:44 UTC
